sudo: false
language: python
install: pip install tox-travis
matrix:
  include:
    - python: 3.5
      env: ENV=lint
    - python: 3.6
      env: ENV=lint
    - python: 3.7
      env: ENV=lint
    - python: 3.8
      env: ENV=lint
    - name: openrc
      env: ENV=openrc
      sudo: required
      dist: bionic
      addons:
        snaps:
          - name: juju
            confinement: classic
          - lxd
          - name: openstackclients
            confinement: classic
comment: |
  install dependencies in script phase saving time on simpler test environments
  change permissions on lxd socket to allow travis user access
  (^^ this is a throw-away CI environment, do not do this at home)
script:
  - if [ $ENV = 'openrc' ]; then
    sudo apt remove -y --purge lxd lxd-client;
      sudo lxd waitready;
      sudo lxd init --auto;
      sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket;
      juju bootstrap --no-gui localhost;
      sh -c 'while true; do echo .; sleep 300; done' &
      tox -c rcs/tox.ini -e func;
      juju switch $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/);
      juju status;
      source rcs/openrc;
      openstack token issue;
      openstack catalog list;
    else
      tox -e $ENV;
    fi
