---
sudo: required
dist: xenial
language: python
env:
 - IMAGE="images:ubuntu/bionic"
script:
 - if [ ! -z ${LINT} ]; then echo "Hello, world!"; fi
# setup dependencies here to save time on simpler test environments
# wait for lxd socket to be ready after snap installation
# sudo back to ourself to activate lxd group membership
 - if [ ! -z ${IMAGE} ]; then
      sudo apt remove -y --purge lxd lxd-client;
      sudo snap install lxd;
      sudo snap install juju --classic
      sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
      sudo lxd waitready;
      sudo usermod -a -G lxd travis;
      sudo su travis -c 'lxc network list';
      sudo su travis -c 'lxc network show lxdbr0';
      sudo ip a;
      sudo lxd init --auto;
      sudo su travis -c 'lxc network list';
      sudo su travis -c 'lxc network show lxdbr0';
   fi
 - if [ ! -z ${IMAGE} ]; then
      sudo su travis -c 'lxc launch ${IMAGE} mymachinecontainer';
      sudo su travis -c 'lxc exec mymachinecontainer -- sh -c "lsb_release -a || cat /etc/redhat-release"';
      sudo su travis -c 'lxc exec mymachinecontainer -- sh -c "ip a"';
      sudo su travis -c 'juju bootstrap --debug --no-gui localhost';
      sudo su travis -c 'juju deploy ubuntu';
      while true; do juju status;sleep 1;done;
   fi
