#!/bin/bash

if [ -z "$1" ]; then
    echo usage: $0 FILE >&2
    echo >&2
    echo "    FILE    - list of floating ips to delete" >&2
    echo >&2
    echo "FILE FORMAT" >&2
    echo "id port_id floating_network_id floating_ip_address" >&2
    echo >&2
    exit
fi
LISTFILE=$1

while read -r line; do
    while read -r id port_id floating_network_id floating_ip_address; do
        neutron floatingip-delete $id
    done <<< "$line"
done <<< `cat $LISTFILE`
