name: test

on:
  push:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo ${{ github.base_ref || github.ref_name }}
          echo ${{ github.base_ref }} || true
          echo ${{ github.ref_name }} || true
